more tests
svn path=/trunk/perl-bindings/; revision=16443

diff --git a/testsuite/test-perl b/testsuite/test-perl
--- a/testsuite/test-perl
+++ b/testsuite/test-perl
@@ -1,3 +1,50 @@
-#! /usr/bin/perl -w
-# ensure that it parses correctly, duh!
-use YaST::YCP;
+#! /bin/sh
+
+# be locale independent
+export LC_ALL=C
+
+# run all test cases or stop at first failure?
+if [ "x$1" = "x-a" -o "x$ALL" != "x" ]; then
+    RUNALL=1
+fi
+
+# set unless overriden
+: ${PREFIX:=/usr}
+: ${PERL:=perl}
+# load modules from the proper directory
+# and plugins
+export Y2DIR=.
+MODDIR=tests
+# for building (DESTDIR is set to RPM_BUILD_ROOT from outside)
+PLUGDIR=${DESTDIR}${PREFIX}/lib/YaST2/plugin
+rm -f $Y2DIR/modules
+ln -s $MODDIR $Y2DIR/modules
+rm -f $Y2DIR/plugin
+ln -s $PLUGDIR $Y2DIR/plugin
+trap "rm -f $Y2DIR/modules $Y2DIR/plugin" EXIT TERM
+
+RET=0
+for SCRIPT in tests/*.pl; do
+    BASE=${SCRIPT%.pl}
+    OUT=$BASE.out
+    ERR=$BASE.err
+    BASE=${BASE#tests/}
+
+    echo ----- $BASE
+    CASEOK=true
+    # y2log to stderr, take specified namespace from Perl
+    $PERL $SCRIPT > tmp.out.$BASE 2> tmp.err.$BASE
+#strace -eopen    $PERL $SCRIPT 2>&1 |grep -v ENOENT
+    # filter out variable information
+    sed --in-place -e 's/^....-..-.. ..:..:.. \(<.> \)[^ ]* /\1/' tmp.err.$BASE
+    sed --in-place -e 's/\(([^)]*)\):[0-9]\+/\1:XXX/' tmp.err.$BASE
+    diff -Nu $ERR tmp.err.$BASE || CASEOK=false
+    diff -Nu $OUT tmp.out.$BASE || CASEOK=false
+
+    if ! $CASEOK; then
+	RET=1
+	[ -n "$RUNALL" ] || break
+    fi
+done
+
+exit $RET
